language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - 12
git:
  depth: 3
script:
  - npm test
notifications:
  slack:
    "JdW0zRESY9kP3IfnxfXBj8gdDWFt+bJ31Xdf0zoXdq+eAlV1hKQPrA5RVXi5i0mE4em6/+R1jbEYlQWqmEapYB8FX1tftPKXSHFeWIU2qmmlx9J4tK/QIfiwM+BTtYIyJQSzG2BeIOUdoxt5GI+KLFIyAUg2clJv6D3UcujT+4A+wqrcRYDUCLKzo5KZs64bIFEIKm87WQfc5yyupKtVIzKNSRVnnHyy/fKSmrlEKsGRef6/C9J2hSwa2IEqZe+XlaeVwJuqOFEJvSB3atICVdKL1MwCP9uCTLHTFAQiGHT3zBmQpw490Pppnf9upP860XfjvS8USIZlfA5Bex5kNhFFfVlCOQD3mxsRsXm42GY55D2Wzd71rsQfRkRLBO/ejW7jft9mbP7qpUki8yxoFo7ZxqBd8FiUMeLQwban+2WD2/5uwXqxU6ohu3vvbTMf22Z1xJZOUyenLV1mICWVwfwMX/e4cfxVkEOzhgeqMu9iUhURnvMfboCTbkSrYg2bdslzEd7IVsUPKi8uiKEhAnZRMisyoi3RN1gddMQ6TnnyxPSlc1GuN2jwf4ZJ4zdcHa6k/B6kgWK1Kr2nlGHSdl1v2QQOdro1gb1B7VggG/5x4L1tncULQIXnHYNFJSWKvSdUQh0Z4g57i7fn2ZM+vtPtTPMaoBsJD01YKpuYBcM="
  email:
    recipients:
      - alver01.12.1990@gmail.com
      - viga.23@hotmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api_key:
    "q/g/TfaDiH3GdAPtCwj7JtpfG+ng8W8TjeoG0/VJ1F+HFuEdevegRmarzCluUooibX2MDAFDoVoZ1fRb9yDPaAWk3aGFG/5rfs/n+8kzAlevl0zk/9ys9pN6FhY7CspXebxP60n7zmPGeiKLtjdEscoDppElAo4kWtDGybS7lWBYnarpt+GjwTV6Rb0emprx2XUr0HIp+UEwBioy/vLe9kyple7AUzGKt6+BegCH9OGu/r16S9qvq17mEJt6YIVz1WaUKKZky8uUVQ5VMkJTNXC8qfoUFAYnQvVpKazLQAphu/ZoacWrMnc9QDCOEZ36FtOqSkr8VBRKuy1rpXKHBUt5Qrdxxl7Zj2rbbkMaT7oyesm43ro9xyw41HivwRkopybkyQ5UW+ZKLLDSDdciP2TeIgvJ/fCWQgy1qaqWdBdg4uSg/AtdSklt9suHfI13Z9Sj3coP4sqo9qUZhzq5BOKHlfMJSwwW6iYH8e3wkbfcXbav46FeAq/FBBhUK4fu3i5GtzkNE2KFHv0PXuOws2ScsCJh8JdoNJhxXhQkozJezJAEyTc1f7fIJDiAQrRjrkpwml7svRRyMeiMEbUTo91lrK/Q/hDWAwlmiEsOOHL0ww2ji00EvBk/7NqG4OAbDdSj/pHa1luOO4j6hv2Wsd46FahrbD/gn7BCR/ExOas="
  app: platzi-store-backed
  on:
    repo: Alver23/platzi-store-backend
